### ISSUE TITLE
devout does not see functions from devoutaudio

### ISSUE THREAD

**Issue by oganm** [coolbutuseless/devoutaudio#1]
Trying to do

```r
library(devoutaudio)

audio()
plot(1:10)
dev.off()
```

you get the error 

```
Warning messages:
1: In (function (rfunction, device_call, state, args)  :
  rdevice: r callback not found: audio_callback
```

This is presumably because devout cannot access the non-exported devoutaudio function `audio_callback`

Creating it in the global environment solves the issue (I get other errors but that's `audio` package's fault), changing the code to call its own functions with `:::` within the package should be a poor man's fix to the issue

```r
audio_callback = function (device_call, args, state) 
{
  state <- switch(device_call, open = devoutaudio:::audio_open(args, state), 
                  close = devoutaudio:::audio_close(args, state),
                  line = devoutaudio:::audio_line(args, state), 
                  polyline = devoutaudio:::audio_polyline(args, state), 
                  circle = devoutaudio:::audio_circle(args, state), 
                  rect = devoutaudio:::audio_rect(args, state), 
                  text = devoutaudio:::audio_text(args,  state), 
                  textUTF8 = devoutaudio:::audio_text(args, state), 
                  polygon = devoutaudio:::audio_polygon(args,  state), 
                  path = devoutaudio:::audio_path(args, state), 
                  circle = devoutaudio:::audio_circle(args, state), state)
  state
}
```

This is likely undetected in a testing environment since internal functions are exported when using `devtools::load_all`

**Comment by coolbutuseless** [comment]
Can you try v0.1.1?

I shifted 'devout' from "Imports" to "Depends" to make sure it's loaded.

**Comment by oganm** [comment]
It works now but switching to depends should not be necessary. `export(audio_callback)` in namespace is what fixes it by itself since devout functions are already used by `::`
`
